apiVersion: v1
kind: Pod
metadata:
  name: spark3
  labels:
    app: spark3
spec:
  containers:
  - name: spark3
    image: ubuntu:22.04
    command: ["sleep", "infinity"]
    ports:
    - containerPort: 4040
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spark3
spec:
  selector:
    app: spark3
  ports:
  - name: spark-ui
    port: 4040
  - name: master-web
    port: 8080
